# Generated by Django 3.0.3 on 2020-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('place_id', models.CharField(help_text='Facebook web page id', max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('config', models.TextField(help_text='String with JSON config of the parser', max_length=5000)),
            ],
        ),
    ]
