# Generated by Django 3.0.3 on 2020-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplace',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
