# Generated by Django 3.0.3 on 2020-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdj', '0002_auto_20200831_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplace',
            name='config',
            field=models.TextField(default='{}', help_text='String with JSON config of the parser', max_length=5000),
        ),
    ]
