# Generated by Django 3.0.3 on 2020-08-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdj', '0002_auto_20200829_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodplace',
            old_name='place_id',
            new_name='fb_place_id',
        ),
    ]
